# Captcha
#
# For support consider joining my discord: https://discord.gg/zgKr2YM

captcha-settings:
  attempts: 3
  color: false
  lines: true
  maps: 1000
  mode: ALL # FIRSTJOIN, ALL, NONE
  op-override: false
  permission-override: true
  time: 600
  update-message: true
  cooldown: "1w"